CREATE TABLE [dbo].[REGION] (
    [R_REGIONKEY] INT           NOT NULL,
    [R_NAME]      CHAR (25)     NOT NULL,
    [R_COMMENT]   VARCHAR (152) NULL,
    [C1]          VARCHAR (100) NULL,
    CONSTRAINT [PK_REGION] PRIMARY KEY CLUSTERED ([R_REGIONKEY] ASC)
);
GO
