-- 可用性グループの作成
CREATE AVAILABILITY GROUP [AG02]
WITH (AUTOMATED_BACKUP_PREFERENCE = SECONDARY,
DB_FAILOVER = ON,
DTC_SUPPORT = PER_DB,
CLUSTER_TYPE = WSFC,
REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 0)
FOR
REPLICA ON
  N'SQLVM-03' WITH (
    ENDPOINT_URL = N'TCP://SQLVM-03.alwayson.local:5022', 
    FAILOVER_MODE = AUTOMATIC, 
    AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, 
    SESSION_TIMEOUT = 10, 
    BACKUP_PRIORITY = 50, 
    SEEDING_MODE = AUTOMATIC
	)
GO

ALTER AVAILABILITY GROUP [AG02] GRANT CREATE ANY DATABASE  
GO  

-- リスナーの作成 (プライマリで実行)
ALTER AVAILABILITY GROUP [AG02]
ADD LISTENER N'SQLVM-2nd-LN' (
WITH IP((N'10.80.1.11', N'255.0.0.0'))
, PORT=1433)
GO

-- 分散型可用性グループの作成 (分散プライマリで実行)
CREATE AVAILABILITY GROUP [DAG01]
WITH (DISTRIBUTED) AVAILABILITY
GROUP ON 
'AG01' WITH (
LISTENER_URL = 'tcp://SQLVM-LN.alwayson.local:5022'
,AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT
,FAILOVER_MODE = MANUAL
,SEEDING_MODE = AUTOMATIC
)
    ,
'AG02' WITH (
LISTENER_URL = 'tcp://SQLVM-2nd-LN.alwayson.local:5022'
,AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT
,FAILOVER_MODE = MANUAL
,SEEDING_MODE = AUTOMATIC
);
GO

-- 分散型可用性グループに参加 (分散セカンダリで実行)
ALTER AVAILABILITY GROUP [DAG01]
   JOIN   
   AVAILABILITY GROUP ON  
      'AG01' WITH    
      (   
         LISTENER_URL = 'tcp://SQLVM-LN.alwayson.local:5022',    
         AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,   
         FAILOVER_MODE = MANUAL,   
         SEEDING_MODE = AUTOMATIC   
      ),   
      'AG02' WITH    
      (   
         LISTENER_URL = 'tcp://SQLVM-2nd-LN.alwayson.local:5022',   
         AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,   
         FAILOVER_MODE = MANUAL,   
         SEEDING_MODE = AUTOMATIC   
      );  
GO  
