USE master
GO

IF DB_ID('DemoDB') IS  NULL
BEGIN
	CREATE DATABASE [DemoDB]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'DemoDB', FILENAME = N'E:\Data\DemoDB.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB ), 
	 FILEGROUP [DemoDB_InMemory] CONTAINS MEMORY_OPTIMIZED_DATA 
	( NAME = N'DemoDB_InMemory', FILENAME = N'E:\Data\DemoDB_InMemory' )
	 LOG ON 
	( NAME = N'DemoDB_log', FILENAME = N'E:\Log\DemoDB_log.ldf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
END
GO
ALTER DATABASE [DemoDB] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [DemoDB] SET RECOVERY SIMPLE 
GO

/*
メモリ最適化テーブル用ファイルグループのみを追加する場合
ALTER DATABASE [DemoDB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [DemoDB] ADD FILEGROUP [InMemory] CONTAINS MEMORY_OPTIMIZED_DATA 
GO
ALTER DATABASE [DemoDB] ADD FILE ( NAME = N'DemoDB_InMemory', FILENAME = N'E:\data\DemoDB_InMemory' ) TO FILEGROUP [InMemory]
GO
*/
