USE DemoDB
GO


IF OBJECT_ID('ORDERS', 'U') IS NOT NULL
	DROP TABLE ORDERS

CREATE TABLE [dbo].[ORDERS](
	[O_ORDERKEY] [int] NOT NULL PRIMARY KEY NONCLUSTERED ,
	[O_CUSTKEY] [int] NOT NULL,
	[O_ORDERSTATUS] [nchar](1) NOT NULL,
	[O_TOTALPRICE] [decimal](15, 2) NOT NULL,
	[O_ORDERDATE] [date] NOT NULL,
	[O_ORDERPRIORITY] [nchar](15) NOT NULL,
	[O_CLERK] [nchar](15) NOT NULL,
	[O_SHIPPRIORITY] [int] NOT NULL,
	[O_COMMENT] [nvarchar](79) NOT NULL
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY)


/*
FOR /L %i IN (1,1,1) DO start bcp dbo.ORDERS in E:\dbgen\orders.tbl.%i -S localhost -d demodb -T -c -t "|" -r 0x0A
*/

USE [master]
GO
ALTER DATABASE [DemoDB] SET COMPATIBILITY_LEVEL = 120
GO
USE [DemoDB]
DBCC FREEPROCCACHE
GO
SELECT O_CUSTKEY,COUNT(*) FROM ORDERS GROUP BY O_CUSTKEY ORDER BY O_CUSTKEY DESC


USE [master]
GO
ALTER DATABASE [DemoDB] SET COMPATIBILITY_LEVEL = 130
GO
USE [DemoDB]
DBCC FREEPROCCACHE
GO
SELECT O_CUSTKEY,COUNT(*) FROM ORDERS GROUP BY O_CUSTKEY ORDER BY O_CUSTKEY DESC
