USE DemoDB
GO

IF OBJECT_ID('NC_PROC1','P') IS NOT NULL
   DROP PROCEDURE NC_PROC1
GO

IF OBJECT_ID('FN_Add','FN') IS NOT NULL
	DROP FUNCTION FN_Add
GO

CREATE FUNCTION dbo.FN_Add 
(
	@p1 int
)
RETURNS int
WITH NATIVE_COMPILATION, SCHEMABINDING
AS
BEGIN ATOMIC
WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'Japanese')
	RETURN @p1 + 1
END
GO


/*
CTP 2.1 までは、以下の構文で作成可能であったが、CTP 2.4 ではネイティブコンパイルのユーザー定義関数として作成する
CREATE FUNCTION dbo.FN_Add 
(
	@p1 int
)
RETURNS int
AS
BEGIN
	RETURN @p1 + 1
END
GO
*/

CREATE PROCEDURE dbo.NC_PROC1
	@p1 nvarchar(100)
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS BEGIN ATOMIC WITH
(
 TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'Japanese'
)
 DECLARE @ret int
 EXECUTE  @ret = dbo.FN_Add @p1 =@p1
 SELECT @ret

 SELECT  dbo.FN_Add(@p1)
END
GO

EXEC dbo.NC_PROC1 1
