IF OBJECT_ID('NC_PROC1','P') IS NOT NULL
   DROP PROCEDURE NC_PROC1
GO

CREATE PROCEDURE dbo.NC_PROC1
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS BEGIN ATOMIC WITH
(
 TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'Japanese'
)
 SELECT 1
 UNION
 SELECT 2
END
GO


IF OBJECT_ID('NC_PROC1','P') IS NOT NULL
   DROP PROCEDURE NC_PROC1
GO
CREATE PROCEDURE dbo.NC_PROC1
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS BEGIN ATOMIC WITH
(
 TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'Japanese'
)
	SELECT Tmp.Col1,Tmp2.Col1 FROM (VALUES(1)) AS Tmp(Col1)
	LEFT JOIN
	(SELECT Col1 FROM (VALUES(1)) AS Tmp(Col1)) AS Tmp2
	ON
	Tmp.Col1 = Tmp2.Col1
END
GO
