USE DemoDB
GO

DROP TABLE IF EXISTS CONSTRAINT_TEST
DROP TABLE IF EXISTS REFTABLE

CREATE TABLE [dbo].[REFTABLE](
	[REF_Col1] int ,
	[REF_CUSTKEY] int PRIMARY KEY NONCLUSTERED
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY)

CREATE TABLE [dbo].[CONSTRAINT_TEST](
	[O_ORDERKEY] [int] NOT NULL UNIQUE,
	[O_CUSTKEY] [int] NOT NULL,
	[O_ORDERSTATUS] [nchar](1) NOT NULL,
	[O_TOTALPRICE] [decimal](15, 2) NOT NULL,
	[O_ORDERDATE] [date] NOT NULL,
	[O_ORDERPRIORITY] [nchar](15) NOT NULL,
	[O_CLERK] [nchar](15) NOT NULL,
	[O_SHIPPRIORITY] [int] NOT NULL,
	[O_COMMENT] [nvarchar](79) NOT NULL,
	CONSTRAINT FK_CONSTRAINT_TEST FOREIGN KEY (O_CUSTKEY)
	REFERENCES [dbo].[REFTABLE] ([REF_CUSTKEY])
	-- カスケードはできない
	-- ON DELETE CASCADE 
	-- ON UPDATE CASCADE
	,CONSTRAINT CK_O_CUSTKEY CHECK (O_CUSTKEY >= 1 )
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY)

