DROP TABLE IF EXISTS #BackupHeader

CREATE TABLE #BackupHeader(
BackupName 	nvarchar(128),
BackupDescription 	nvarchar(255),
BackupType 	smallint,
ExpirationDate 	datetime,
Compressed 	bit,
Position 	smallint,
DeviceType 	tinyint,
USERNAME 	nvarchar(128),
ServerName 	nvarchar(128),
DatabaseName 	nvarchar(128),
DatabaseVersion 	int,
DatabaseCreationDate 	datetime,
BackupSize 	numeric(20,0),
FirstLSN 	numeric(25,0),
LastLSN 	numeric(25,0),
CheckpointLSN 	numeric(25,0),
DatabaseBackupLSN 	numeric(25,0),	
BackupStartDate 	datetime,
BackupFinishDate 	datetime,
SortOrder 	smallint,
CodePage 	smallint,
UnicodeLocaleId 	int,
UnicodeComparisonStyle 	int,
CompatibilityLevel 	tinyint,
SoftwareVendorId 	int,
SoftwareVersionMajor 	int,
SoftwareVersionMinor 	int,
SoftwareVersionBuild 	int,
MachineName 	nvarchar(128),
Flags 	int,
BindingID 	uniqueidentifier,
RecoveryForkID 	uniqueidentifier,
Collation 	nvarchar(128),
FamilyGUID 	uniqueidentifier,
HasBulkLoggedData 	bit,
IsSnapshot 	bit,
IsReadOnly 	bit,
IsSingleUser 	bit,
HasBackupChecksums 	bit,
IsDamaged 	bit,
BeginsLogChain 	bit,
HasIncompleteMetaData 	bit,
IsForceOffline 	bit,
IsCopyOnly 	bit,
FirstRecoveryForkID 	uniqueidentifier,
ForkPointLSN 	numeric(25,0) NULL ,
RecoveryModel 	nvarchar(60),	
DifferentialBaseLSN 	numeric(25,0) NULL ,
DifferentialBaseGUID 	uniqueidentifier,
BackupTypeDescription 	nvarchar(60),
BackupSetGUID 	uniqueidentifier NULL ,
CompressedBackupSize 	bigint,
containment	tinyint,
KeyAlgorithm nvarchar(32),
EncryptorThumbprint varbinary(20),
EncryptorType nvarchar(32)  
)

INSERT INTO #BackupHeader EXEC ('RESTORE HEADERONLY FROM DISK=N''BULKDB.bak''' ) 
	
SELECT DatabaseName, BackupStartDate, BackupFInishDate, HasBulkLoggedData, RecoveryModel
FROM #BackupHeader

