USE DemoDB
GO

	
IF OBJECT_ID('TSQLTEST', 'U') IS NOT NULL
	DROP TABLE TSQLTEST

IF EXISTS (SELECT 1 FROM  sys.partition_schemes where name = 'TSQLTESTPS')
	DROP  PARTITION SCHEME TSQLTESTPS


IF EXISTS (SELECT 1 FROM  sys.partition_functions where name = 'TSQLTESTPF')
	DROP PARTITION FUNCTION TSQLTESTPF


CREATE PARTITION FUNCTION TSQLTESTPF (int)
AS RANGE LEFT FOR VALUES (1, 2, 3)

CREATE PARTITION SCHEME TSQLTESTPS AS PARTITION TSQLTESTPF ALL TO ([PRIMARY])

CREATE TABLE TSQLTEST(
	Col1 int,
	Col2 char(100)
) ON TSQLTESTPS(Col1)


SET NOCOUNT ON
GO
INSERT INTO TSQLTEST VALUES (1, NEWID()), (2, NEWID()), (3, NEWID()), (4, NEWID())

SELECT * FROM TSQLTEST

TRUNCATE TABLE TSQLTEST WITH(PARTITIONS (3))

SELECT * FROM TSQLTEST
