USE master
GO
DROP DATABASE DB01
GO

CREATE DATABASE DB01
GO

USE DB01
GO
 
ALTER DATABASE SCOPED CONFIGURATION SET FULLTEXT_INDEX_VERSION = 2;
GO
 
CREATE FULLTEXT CATALOG [FtCatalog] WITH ACCENT_SENSITIVITY = ON AS DEFAULT
GO
 
DROP TABLE IF EXISTS [dbo].[FT_TEST]
GO
 
CREATE TABLE [dbo].[FT_TEST](
      [C1] [int] IDENTITY(1,1) NOT NULL,
      [C2] [nvarchar](max) NULL
)
GO
 
ALTER TABLE [dbo].[FT_TEST] ADD CONSTRAINT PK_FT_TEST PRIMARY KEY CLUSTERED(C1)
GO
 
CREATE FULLTEXT INDEX ON [dbo].[FT_TEST](C2 LANGUAGE Japanese)
   KEY INDEX PK_FT_TEST
   WITH CHANGE_TRACKING=AUTO
GO
 
INSERT INTO FT_TEST VALUES(N'テスト')
GO
 
ALTER FULLTEXT CATALOG [FtCatalog] REBUILD;
GO

-- 正常に動作する
SELECT * FROM FT_TEST WHERE CONTAINS(C2 , 'テスト', LANGUAGE 'Japanese');  
GO

SELECT * FROM FT_TEST WHERE CONTAINS(C2 , 'NEAR((bike,control), 10, TRUE)', LANGUAGE 'Japanese');  
GO

SELECT * FROM FT_TEST WHERE CONTAINS(C2 , 'ISABOUT (performance weight (.8), comfortable weight (.4), smooth weight (.2) )', LANGUAGE 'Japanese');  
GO

-- ERROR が発生する
SELECT * FROM FT_TEST WHERE CONTAINS(C2 , ' FORMSOF (INFLECTIONAL, ride) ', LANGUAGE 'Japanese');  
GO

SELECT * FROM FREETEXTTABLE(FT_TEST, C2, N'テスト', LANGUAGE N'Japanese') AS ft
GO

SELECT * FROM FT_TEST WHERE FREETEXT (C2, N'テスト', LANGUAGE N'Japanese') 
GO

