SELECT
    DB_NAME(eps.database_id) AS database_name,
    OBJECT_NAME(eps.object_id, eps.database_id) AS object_name,
    eps.type_desc,
    eps.cached_time,
    eps.last_execution_time,
    eps.execution_count,
    (eps.total_worker_time / 1000.0) AS total_worker_time_ms,
    (eps.last_worker_time / 1000.0) AS last_worker_time_ms,
    (eps.min_worker_time / 1000.0) AS min_worker_time_ms,
    (eps.max_worker_time / 1000.0) AS max_worker_time_ms,
    (eps.total_worker_time / eps.execution_count / 1000.0) AS avg_worker_time_ms,
    eps.total_physical_reads,
    eps.last_physical_reads,
    eps.min_physical_reads,
    eps.max_physical_reads,
    (eps.total_physical_reads / eps.execution_count) AS avg_physical_reads,
    eps.total_logical_writes,
    eps.last_logical_writes,
    eps.min_logical_writes,
    eps.max_logical_writes,
    eps.total_logical_reads,
    eps.last_logical_reads,
    eps.min_logical_reads,
    eps.max_logical_reads,
    (eps.total_logical_writes / eps.execution_count) AS avg_logical_reads,
    eps.total_elapsed_time,
    eps.last_elapsed_time,
    eps.min_elapsed_time,
    eps.max_elapsed_time,
    (eps.total_elapsed_time / eps.execution_count) AS avg_elapsed_time,
    eps.total_spills,
    eps.last_spills,
    eps.min_spills,
    eps.max_spills,
    eps.total_num_physical_reads,
    eps.last_num_physical_reads,
    eps.min_num_physical_reads,
    eps.max_num_physical_reads,
    (eps.total_num_physical_reads / eps.execution_count) AS avg_num_physical_reads,
    eps.total_page_server_reads,
    --eps.last_page_server_reads,
    --eps.min_page_server_reads,
    --eps.max_page_server_reads,
    --eps.total_num_page_server_reads,
    --eps.last_num_page_server_reads,
    --eps.min_num_page_server_reads,
    --eps.max_num_page_server_reads,
    est.text,
    eqp.query_plan,
    eps.sql_handle,
    eps.plan_handle
FROM
    sys.dm_exec_procedure_stats AS eps
    OUTER APPLY sys.dm_exec_sql_text(sql_handle) AS est
    OUTER APPLY sys.dm_exec_query_plan(plan_handle) AS eqp
WHERE
    database_id <> 32767