-- DBCC のコマンド一覧 / ヘルプ確認 (アンドキュメント含む)
DBCC TRACEON(2588) WITH NO_INFOMSGS
DBCC HELP('?') WITH NO_INFOMSGS
DBCC HELP('WRITEPAGE') WITH NO_INFOMSGS
DBCC TRACEOFF(2588) WITH NO_INFOMSGS

-- バッファキャッシュのクリア
DBCC DROPCLEANBUFFERS

-- プランキャッシュのクリア
DBCC FREEPROCCACHE
DBCC FLUSHPROCINDB(<DB ID>)

-- ページ情報の確認
DBCC TRACEON(3604) 
DBCC PAGE(N'TEST', 1, 128, 1) 
DBCC TRACEOFF(3604)

-- ページ情報の書き換え
ALTER DATABASE TEST SET SINGLE_USER
DBCC WRITEPAGE ('TEST', 1, 179, 1, 1, 0x00, 1)
ALTER DATABASE TEST SET MULTI_USER


-- IO の凍結
DBCC FREEZE_IO (<DB 名>)

-- IO の凍結の解除
DBCC THAW_IO (<DB 名>)

-- クローンデータベースの作成 (SQL Server 2014 SP2) 
DBCC CLONEDATABASE(AdventureWorks2014, AWCloneDB)
 


