-- DBCC のコマンド一覧 / ヘルプ確認 (アンドキュメント含む)
DBCC TRACEON(2588) WITH NO_INFOMSGS
DBCC HELP('?') WITH NO_INFOMSGS
DBCC HELP('WRITEPAGE') WITH NO_INFOMSGS
DBCC TRACEOFF(2588) WITH NO_INFOMSGS

-- バッファキャッシュのクリア
DBCC DROPCLEANBUFFERS

-- プランキャッシュのクリア
DBCC FREEPROCCACHE
DBCC FLUSHPROCINDB(<DB ID>)


-- キャッシュクリア
DBCC FREESYSTEMCACHE('ALL')


-- ページ情報の確認
DBCC TRACEON(3604) 
DBCC PAGE(N'tpch', 1, 128, 1) 
DBCC PAGE(N'tpch', 1, 128, 1) WITH TABLERESULTS -- 3604 を有効にしないでも出力可能
DBCC PAGE(0, 1, 128, 1) WITH TABLERESULTS -- DBCC 全般として dbid=0 で 現在の DB の情報を出力
DBCC TRACEOFF(3604)

-- ページ情報の書き換え
ALTER DATABASE TEST SET SINGLE_USER
DBCC WRITEPAGE ('TEST', 1, 179, 1, 1, 0x00, 1)
ALTER DATABASE TEST SET MULTI_USER


-- IO の凍結
DBCC FREEZE_IO (<DB 名>)

-- IO の凍結の解除
DBCC THAW_IO (<DB 名>)

-- クローンデータベースの作成 (SQL Server 2014 SP2) 
DBCC CLONEDATABASE(AdventureWorks2014, AWCloneDB)
 


-- DB の各種情報の取得
DBCC TRACEON(3604)

DBCC DBINFO -- Database Metadata

DBCC PAGE('tpch',1,9,3); -- Boot Page でも DBINO 相当の情報を確認可能

DBCC FILEHEADER(0,1) -- 現在の DB の  File ID 1 のヘッダー情報を出力

DBCC DBTABLE('tpch') -- Database の DB テーブル構造を出力

DBCC TRACEOFF(3604)
