SELECT 
    CASE WHEN (@@OPTIONS & 16384) >0    THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 8192) > 0    THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 4096) > 0    THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 2048) > 0    THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 1024) > 0    THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 512) > 0     THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 256) > 0     THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 128) > 0     THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 64) > 0      THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 32) > 0      THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 16) > 0      THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 8) > 0       THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 4) > 0       THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 2) > 0       THEN '1' ELSE '0' END +
    CASE WHEN (@@OPTIONS & 1) > 0       THEN '1' ELSE '0' END
    AS set_option,
    CASE WHEN (@@OPTIONS & 16384) >0    THEN 'XACT_ABORT;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 8192) > 0    THEN 'NUMERIC_ROUNDABORT;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 4096) > 0    THEN 'CONCAT_NULL_YIELDS_NULL;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 2048) > 0    THEN 'ANSI_NULL_DFLT_OFF;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 1024) > 0    THEN 'ANSI_NULL_DFLT_ON;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 512) > 0     THEN 'NOCOUNT;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 256) > 0     THEN 'QUOTED_IDENTIFIER;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 128) > 0     THEN 'ARITHIGNORE;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 64) > 0      THEN 'ARITHABORT;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 32) > 0      THEN 'ANSI_NULLS;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 16) > 0      THEN 'ANSI_PADDING;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 8) > 0       THEN 'ANSI_WARNINGS;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 4) > 0       THEN 'CURSOR_CLOSE_ON_COMMIT;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 2) > 0       THEN 'IMPLICIT_TRANSACTIONS;' ELSE '' END +
    CASE WHEN (@@OPTIONS & 1) > 0       THEN 'DISABLE_DEF_CNST_CHK;' ELSE '' END
    AS set_option_desc