use [tpch]
GO


SET STATISTICS PROFILE ON
GO

-- For table REGION
ALTER TABLE REGION
ADD CONSTRAINT PK_REGION PRIMARY KEY (R_REGIONKEY);
GO

-- For table PART
ALTER TABLE PART
ADD CONSTRAINT PK_PART PRIMARY KEY (P_PARTKEY);
GO

-- For table SUPPLIER
ALTER TABLE SUPPLIER
ADD CONSTRAINT PK_SUPPLIER PRIMARY KEY (S_SUPPKEY);

ALTER TABLE SUPPLIER 
ADD CONSTRAINT SUPPLIER_FK1 FOREIGN KEY(S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
GO

-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD CONSTRAINT PK_PARTSUPP PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);
GO

-- For table CUSTOMER
ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (C_CUSTKEY);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_FK1 FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY);
GO

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD CONSTRAINT PK_LINEITEM PRIMARY KEY (L_ORDERKEY,L_LINENUMBER) WITH(DATA_COMPRESSION=PAGE);
GO

-- For table ORDERS
ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS PRIMARY KEY (O_ORDERKEY);
GO

-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD CONSTRAINT PARTSUPP_FK1 FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY);

ALTER TABLE PARTSUPP
ADD CONSTRAINT PARTSUPP_FK2 FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY);
GO

-- For table ORDERS
ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);
GO

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD CONSTRAINT LINEITEM_FK1 FOREIGN KEY (L_ORDERKEY)  REFERENCES ORDERS(O_ORDERKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT LINEITEM_FK2 FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES PARTSUPP (PS_PARTKEY,PS_SUPPKEY);
GO


/*

-- For table REGION
ALTER TABLE REGION
ADD CONSTRAINT PK_REGION PRIMARY KEY (R_REGIONKEY);
GO

-- For table NATION
ALTER TABLE NATION
ADD CONSTRAINT PK_NATION PRIMARY KEY (N_NATIONKEY);

-- For table PART
ALTER TABLE PART
ADD CONSTRAINT PK_PART PRIMARY KEY (P_PARTKEY);
GO

-- For table SUPPLIER
ALTER TABLE SUPPLIER
ADD CONSTRAINT PK_SUPPLIER PRIMARY KEY (S_SUPPKEY);

-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD CONSTRAINT PK_PARTSUPP PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);
GO

-- For table CUSTOMER
ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (C_CUSTKEY);

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD CONSTRAINT PK_LINEITEM PRIMARY KEY (L_ORDERKEY,L_LINENUMBER) WITH(DATA_COMPRESSION=PAGE);
GO

-- For table ORDERS
ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS PRIMARY KEY (O_ORDERKEY);
GO



*/