USE [master] 
GO 
ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT 
GO 
ALTER DATABASE [DemoDB] SET ALLOW_SNAPSHOT_ISOLATION ON
GO


-- セッション A で実行
USE DemoDB
GO
BEGIN TRAN 
UPDATE ORDERS_CI SET O_ORDERSTATUS = 'A' WHERE O_ORDERKEY = 29373541 
ROLLBACK TRAN

-- セッション B で実行 
USE DemoDB
GO
SELECT O_CUSTKEY,COUNT(*) FROM ORDERS_CI GROUP BY O_CUSTKEY 
 


ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT 
GO 
ALTER DATABASE [DemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
